name: Test Composite Action

on: [workflow_dispatch]

jobs:
  run-action:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Run my composite action
        id: greet_step
        uses: ./.github/actions/greet-action
        with:
          who-to-greet: '${{ github.actor }}'

      - name: Use the output
        run: echo "The time was ${{ steps.greet_step.outputs.current-time }}"
